### ISSUE TITLE
[READ FIRST] Issue Requirements

### ISSUE THREAD

**Issue by np98765** [HarryPotterSpells/HarryPotterSpells#1]
When creating an issue, please include the following information:
- CraftBukkit version (use /version)
- HarryPotterSpells version
- List of plugins (use /pl)
- Complete server log

If it's a configuration issue, please also supply the config file.

You can use [pastebin.com](http://www.pastebin.com) for the server log and configuration file.

**Comment by kingsofbart** [comment]
Hi,

can you update harrypotterspells to 1.8 spigot?

gr bart

**Comment by jacklin213** [comment]
No longer needed as github now supports issue templates
