### ISSUE TITLE
The Plugin HarryPotterSpells doesn´t work.

### ISSUE THREAD

**Issue by Karnal** [HarryPotterSpells/HarryPotterSpells#19]
Hello!
The problem is: There is no config but a empty language file called "us-english.properties" in the plugin folder. So no command is working, but the plugin is listed, when I do /pl.

Thanks for help,
## Karnal

CraftBukkit version: version git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks (MC: 1.7.9) (Implementing API version 1.7.9-R0.2)

HarryPotterSpells version: HarryPotterSpells v1.0 for CB 1.7.9-R0.2 Aug 23, 2014

Plugins: Plugins (23): [0;32;1mMultiWorld[0;37;1m, [0;32;1mTelePads[0;37;1m, [0;32;1mWorldEdit[0;37;1m, [0;32;1mAntiCheat[0;37;1m, [0;32;1mSecureLoginPVP[0;37;1m, [0;32;1mVault[0;37;1m, [0;32;1mPermissionsEx[0;37;1m, [0;31;1mMCTowns[0;37;1m, [0;32;1mHarryPotterSpells[0;37;1m, [0;32;1mBetterShops[0;37;1m, [0;32;1mPortableLight[0;37;1m, [0;32;1mEssentials[0;37;1m, [0;32;1mCitizens[0;37;1m, [0;32;1mPunishmental[0;37;1m, [0;32;1mEssentialsProtect[0;37;1m, [0;32;1mMagicSpells[0;37;1m, [0;32;1mEssentialsSpawn[0;37;1m, [0;32;1mSentry[0;37;1m, [0;32;1mTaxes[0;37;1m, [0;32;1mEssentialsChat[0;37;1m, [0;32;1mBuilder[0;37;1m, [0;32;1mEssentialsAntiBuild[0;37;1m, [0;32;1mMagicSpellsShop[m

Server log: http://pastebin.com/8rTPkMrP

**Comment by jacklin213** [comment]
Sorry @Karnal quick question, what operating system did you have at that time
