### ISSUE TITLE
Not generating any files

### ISSUE THREAD

**Issue by phatfinger5** [HarryPotterSpells/HarryPotterSpells#20]
This is the first time I got the plugin and it does not work.  It wont generate the files that it needs.  I would try to fix it by moving the us language file that has not been generating, but there is no files to put it in.  I would also try getting a new bukkit version, but of course I cant....

I have tried both craftbukkit and spigot.

My CraftBukkit version is: git-Bukkit-1.7.2-R0.3-30-ge027d69-b3058jinks (MC: 1.7.9) (Implementing API version 1.7.9-R0.1-SNAPSHOT

My plugin list: WorldEdit, Easy_Plant, Essentials, EssentialsProtect, HorseMount, EssentialsChat, EssentialsAntiBuild, PermissionsEx, HarryPotterSpells, Modifyworld, TutorialSpawn, Vault, EssentialsSpawn, WorldGuard, Houses, ChestCommands

**Comment by jacklin213** [comment]
@phatfinger5 Not sure if your still interested but download [v.1.1.3](http://dev.bukkit.org/media/files/872/138/HarryPotterSpells.jar) and download [hps.rar](https://github.com/HarryPotterSpells/HarryPotterSpells/raw/master/hps.rar), extract the locale folder directly into your HarryPotterSpells folder, and the plugin should work fine

**Comment by phatfinger5** [comment]
I think we had already fixed it, unless this is just a new update... in
which case I no longer have a server.
