### ISSUE TITLE
[HPS] An error occured whilst generating a Particle Effect!

### ISSUE THREAD

**Issue by xDarkSkyZ** [HarryPotterSpells/HarryPotterSpells#32]
Hey !
![capture](https://cloud.githubusercontent.com/assets/12575131/7784938/2fc8cf5e-0179-11e5-82f6-8eb73945ce81.JPG)

I'm just here to post a bit question : In the console on my server, this message is dislay when I use a spell : [HPS] An error occured whilst generating a Particle Effect!

I give you an image to see the problem.

I'm in the last version of HPS, HarryPotterSpells v1.1.3.

Thanks & bye for reading !

(Sorry for my bad english, I'm french ^.^)

**Comment by jacklin213** [comment]
We are aware of this bug and will fix it soon, thanks for making an issue :)

**Comment by xDarkSkyZ** [comment]
Hey !
Thanks to answer.

Just a bit question : Approximately when will it be available ?

**Comment by jacklin213** [comment]
I'd love to say within this week, but definitely by next week

**Comment by xDarkSkyZ** [comment]
Thanks ! <3
