### ISSUE TITLE
[1.7.10] Alohomora working, but not rendering graphically 

### ISSUE THREAD

**Issue by CoderInOrbit** [HarryPotterSpells/HarryPotterSpells#43]
Hello,

Casting Alohomora opens iron doors, but the iron door does not show as opened, even though it is. The opening animation of the door did not trigger, so the door looks closed, but isn't. Additionally, it never closes, and the spell text seems to be rendering 3 or 4 times for some reason.

Additionally, error in the console : 

>02.07 09:26:54 [Server] WARN at com.hpspells.core.util.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1392)
>02.07 09:26:54 [Server] WARN at com.hpspells.core.util.ReflectionUtils$PackageType.getClass(ReflectionUtils.java:414)
>02.07 09:26:53 [Server] WARN at java.lang.Class.forName(Unknown Source)
>02.07 09:26:53 [Server] WARN at java.lang.Class.forName0(Native Method)
>02.07 09:26:53 [Server] WARN Caused by: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutWorldParticles
>02.07 09:26:53 [Server] WARN at java.lang.Thread.run(Unknown Source)
>02.07 09:26:53 [Server] WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
>02.07 09:26:53 [Server] WARN at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
>02.07 09:26:53 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
>02.07 09:26:53 [Server] WARN at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862)
>02.07 09:26:53 [Server] WARN at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
>02.07 09:26:53 [Server] WARN at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
>02.07 09:26:53 [Server] WARN at com.hpspells.core.Listeners$1.run(Listeners.java:155)
>02.07 09:26:53 [Server] WARN at com.hpspells.core.spell.SpellManager.cleverCast(SpellManager.java:222)
>02.07 09:26:53 [Server] WARN at com.hpspells.core.spell.Alohomora.cast(Alohomora.java:33)
>02.07 09:26:53 [Server] WARN at com.hpspells.core.SpellTargeter.register(SpellTargeter.java:213)
>02.07 09:26:53 [Server] WARN at com.hpspells.core.SpellTargeter.register(SpellTargeter.java:201)
>02.07 09:26:53 [Server] WARN at com.hpspells.core.SpellTargeter$3.run(SpellTargeter.java:177)
>02.07 09:26:53 [Server] WARN at com.hpspells.core.util.ParticleEffect.display(ParticleEffect.java:567)
>02.07 09:26:53 [Server] WARN at com.hpspells.core.util.ParticleEffect$ParticlePacket.<init>(ParticleEffect.java:1332)
>02.07 09:26:53 [Server] WARN at com.hpspells.core.util.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1398)
>02.07 09:26:53 [Server] WARN com.hpspells.core.util.ParticleEffect$ParticlePacket$VersionIncompatibleException: Your current bukkit version seems to be incompatible with this library
>02.07 09:26:53 [Server] WARN An error occurred whilst generating a Particle Effect!`

I am using the latest version of HPS posted on Jenkins.
Thank you

**Comment by jacklin213** [comment]
@CoderInOrbit Version 1.1.4 only works for bukkit/spigot 1.8 +
