### ISSUE TITLE
[1.8.8] How to disable any messages in the chat ?

### ISSUE THREAD

**Issue by BayKoZ** [HarryPotterSpells/HarryPotterSpells#46]
Hi everyone ! :+1: 

I'm here to ask you to how to disable any messages in the chat ?
I want to disable the most painful message :rage: 

![github_hps1](https://cloud.githubusercontent.com/assets/13684416/9122665/cfda6f1a-3c8a-11e5-837f-e2d62271460c.JPG)

But before, any informations..

CraftBukkit version : Spigot 1.8.8-R.01-SNAPSHOT

HarryPotterSpells version : the latest version, 1.1.4

List of plugins : WorldEdit, all Essentials plugins (by vTeamCity) + Essentials GeoIP (by vTeamCity), WorldGuard & HarryPotterSpells ^^

Complete server log : http://pastebin.com/iRwAtB1Y

I'm french so my english is not very well ! :fr: 

So thanks you if you find a solution ! :dancer: 

Bye ! <3

Bay'

**Comment by jacklin213** [comment]
@BayKoZ That message is ment to be displayed as some spells can only be used on a player or mob. The message is appearing because someone isn't aiming properly

Regards
Jack
