### ISSUE TITLE
[1.8.1] Specific spell permission not working.

### ISSUE THREAD

**Issue by Zeddart** [HarryPotterSpells/HarryPotterSpells#48]
As i wan't to prevent players from using Avada Kedavra and some other OverPowered spells i tried using the permission node "harrypotterspells.spell.<spell>". After trying alot of different names "Avada_Kedavra, Avada-Kedavra, AvadaKedavra" and so on. Nothing seems to work. They still don't get the permission.

Thank you for taking the time to read my next issue =3

**Comment by jacklin213** [comment]
Spells with spaces in them now should work by replacing the space with a "-"

eg) Avada Kedavra = harrypotterspells.spell.avada-kedavra
