### ISSUE TITLE
[1.8.1] Expelliarmus not working correctly.

### ISSUE THREAD

**Issue by Zeddart** [HarryPotterSpells/HarryPotterSpells#50]
One of my admins have reported that Expelliarmus does not disarm players, does not matter if it is wands or weapons.

*Information not given in my last issues:*
Server Client: Spigot 1.8.7-Ro1-SNAPSHOT

HPS Version: Latest

Dynmap, Acceptrules, Mcdocs, Worldedit, Questioner, Openinv, Essentials, Logblock, Blothera Thief, ConsoleScheduler, Votifier, Protocollib, Worldguard,  Brewery, Nocheatplus, Frozen (Freezes players for admins), Deathmessages, Iconomy, PEX, Treeassist, Simplevotelistener, Vault, Combattag, Messagefilter, Essentialsspawn, Chetshop, Herochat, Towny, Jobs, Coloredtags, Vanishnopacket, mcmmo, Bounty, dynmap-Towny, Titlemanager, infoboardreborn

Log information: The log reaches back months,

Thank you for taking the time reading this issue =)

**Comment by jacklin213** [comment]
Thanks for reporting this, Download the latest build from our jenkins server and it should be fixed
