### ISSUE TITLE
Problem with permissions

### ISSUE THREAD

**Issue by Deltazura** [HarryPotterSpells/HarryPotterSpells#56]
Hi, I put the permission HarryPotterSpells.teach but the group who have this perm cannot teach spells : 
"You cannot teach Primordius Incendio as you do not know it."
Can you help me ?

**Comment by jacklin213** [comment]
The people who are trying to teach the spell need to have learnt the spells themselves. Either get an op to teach them the spell or have someone who knows the spell to teach it to them
