### ISSUE TITLE
1.12.2 does not working?

### ISSUE THREAD

**Issue by Rowz** [HarryPotterSpells/HarryPotterSpells#63]
Hey, i got an error. I asked a developer and he says i can send this 2 errors to you:
at com.hpspells.core.HPS.onEnable(HPS.java:80) ~[?:?]
14:19:32     at com.hpspells.core.HPS.onEnable(HPS.java:80) ~[?:?]

The whole error is here: 
https://hastebin.com/dofidiriri.go

**Comment by jacklin213** [comment]
I will need to update the plugin, I'll try get it done as soon as possible

**Comment by jacklin213** [comment]
Sorry, Been held up for a bit. Should be done this weekend
