### ISSUE TITLE
Plugin prevents players from dying banners and extending maps.

### ISSUE THREAD

**Issue by FreralCat** [HarryPotterSpells/HarryPotterSpells#67]
Hi, I have deducted that HPS is preventing players from dying banners and extending maps. I am certain about this as I have just uninstalled it and players can now craft bigger maps and dye banners once more. I haven't uninstalled any other plugins with it. The server has recently transferred over from Bukkit 1.12.2 to Spigot 1.12.2 although this issue has been occurring on both plugin platforms. I've been using the latest version of this plugin (v1.1.8). The server is currently running the following plugins:
WorldEdit, Questioner, KeepItems, ClearLag, WarningManager, PermissionsHealthRecoded, HolographicDisplays, Broadcaster, WorldGuard, PermissionsEx, IgnoreMe, mcMMO, Vault, CustomEnchantments, AntiFlyInRegions, Essentials, SimpleRename, Jobs, CrateReloaded, Citizens, EssentialsXMPP, EssentialsProtect, CrazyAuctions, EssentialsAntiBuild, EssentialsSpawn, Towny, RandomTP, TownyChat, TownyNameUpdater.
I'd really like to keep using this plugin on my server but I don't want to have to restrict a vanilla feature in order to keep it. I hope there is something that can be done to fix this. Thank you for your time in advance.

**Comment by jacklin213** [comment]
Hi FreralCat, 
Thanks for reporting this issue, I shall do some testing to see if I can reproduce this bug. I will keep this thread updated
Regards
Jack

**Comment by jacklin213** [comment]
I have confirmed both bugs, will begin looking into it on the 16th (I have exams this week)
Thanks for your understanding

**Comment by FreralCat** [comment]
Thank you for looking into this. I'm more than happy to wait, school is
much more important. I look forward to your verdict later on and good luck
on your exams. :)

**Comment by jacklin213** [comment]
Found the problem and fixed it, you should see an official release coming out soon for the next few days. I have tested that both extended maps and dying banners now work again :D
