### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Oogoid35** [HarryPotterSpells/HarryPotterSpells#70]
I can not find any command. wand can be done without using commands. please type the commands

**Comment by FreralCat** [comment]
**Hi again, commands haven't been working at all and this is what appears in the console on startup. I'm using a spigot 1.12.2 build and have the following plugins:**
_WorldEdit, Questioner, KeepItems, ClearLag, WarningManager, PermissionsHealthRecoded, HolographicDisplays, Broadcaster, WorldGuard, PermissionsEx, IgnoreMe, HarryPotterSpells, mcMMO, Vault, CustomEnchantments, AntiFlyInRegions, Essentials, SimpleRename, Jobs, CrateReloaded, Citizens, EssentialsXMPP, EssentialsProtect, CrazyAuctions, EssentialsAntiBuild, EssentialsSpawn, Towny, RandomTP, TownyChat, TownyNameUpdater_
**This is what appears in my config:**
_

> 08.07 15:31:51 [Server] WARN An error occurred whilst registering some/all of the commands.
> 08.07 15:31:51 [Server] INFO Registered 1 wand materials!
> 08.07 15:31:51 [Server] WARN An error occurred whilst registering some/all of the spells.

_

**Comment by jacklin213** [comment]
@FreralCat I ran HPS v1.1.9 on the stable 1.12.2 spigot release and the commands loaded/worked fine (as shown in the screenshots) 
Could I get you to tell me which version of HPS you are using and send me you config.yml file as well as any other errors shown in your console
Thanks

![image](https://user-images.githubusercontent.com/1115240/42692482-fbe01a8e-86ff-11e8-80b7-6fe31a540fd3.png)

![image](https://user-images.githubusercontent.com/1115240/42692535-24a8bb56-8700-11e8-85a6-35e87973c179.png)

**Comment by FreralCat** [comment]
Hi Jacklin,
I'm using HPS version 1.19 and this is what the config file looks like:

 

> #
> # Should we allow spells to be craftable into books?
> debug-mode: true
> language: us-english
> messaging:
>   tag: '&f[&6HarryPotterSpells&f] '
>   info: YELLOW
>   warning: RED
> wand:
>   types:
>   - stick
>   - blaze_rod
>   - iron_hoe
>   explosion-effect: false
>   enchantment-effect: true
>   lore:
>     name: '&3Wand'
>     enabled: true
>     show-current-spell: true
>     format:
>     - '&eCurrent Spell: &6%spell'
>     - '&b%length&r inches'
>     - '&b%core&r core'
>     - '&b%wood&r wood (&o%rarity&r)'
>     - '%rigidity'
>     - Manufactured by &b%manufacturer
>     length:
>       minimum: 9
>       maximum: 18
>     wood-types:
>       '1':
>       - Elder
>       '2':
>       - Cherry
>       '3':
>       - Apple
>       - Holly
>       - Yew
>       '4':
>       - Acacia
>       - Birch
>       - Ivy
>       - Oak
>       - Red
>       - Rose
>       - Silver Lime
>       - Vine
>       - Willow
>       '5':
>       - Alder
>       - Aspen
>       - Beech
>       - Blackthorn
>       - Black Walnut
>       - Cedar
>       - Cypress
>       - Dog
>       - Ebony
>       - Elm
>       - Fir
>       - Hawthorn
>       - Hazel
>       - Hornbeam
>       - Larch
>       - Laurel
>       - Mahogany
>       - Maple
>       - Pear
>       - Poplar
>       - Reed
>       - Rowan
>       - Spruce
>       - Sycamore
>       - Walnut
>       '6':
>       - Ash
>       - Chesnut
>       - Pine
>     cores:
>       Dragon_heartstring: 0.3
>       Phoenix_feather: 9.0E-4
>       Unicorn_tail_hair: 0.3
>       Veela_hair: 0.133
>       Thestral_tail_hair: 1.0E-4
>       Troll_whisker: 0.133
>       Coral: 0.133
>     manufacturers:
>       Arturo_Cephalopos: 0.0094
>       Antioch_Peverell: 5.0E-4
>       Death: 1.0E-4
>       Mykew_Gregorovitch: 0.1
>       Jimmy_Kiddell: 0.2
>       Ollivander_family: 0.69
>     rigidity:
>     - Very unyielding
>     - Quite unyielding
>     - Quite springy
>     - Very springy
>   crafting:
>     enabled: true
>     recipe:
>     - ' A '
>     - ' B '
>     - ' C '
>     ingredients:
>       A: ghast tear
>       B: nether star
>       C: stick
> spells-craftable: true
> shout-on-spell-use: false
> notify-on-spell-use: true
> spell-particle-toggle: false
> spell-castable-with-chat: true
> spell-effective-time: -1
> 

And this is what appeared in the console:

> 14.07 21:20:35 [Server] INFO Debug: Extension Manager started.
14.07 21:20:35 [Server] INFO Debug: Starting Extension Manager...
14.07 21:20:35 [Server] INFO Debug: Crafting modifications complete.
14.07 21:20:34 [Server] INFO Debug: Starting crafting modification...
14.07 21:20:34 [Server] INFO Debug: Added commands to help.
14.07 21:20:34 [Server] INFO Debug: Registered 0 core commands.
14.07 21:20:34 [Server] WARN at java.lang.Thread.run(Unknown Source)
14.07 21:20:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
14.07 21:20:34 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
14.07 21:20:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
14.07 21:20:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
14.07 21:20:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
14.07 21:20:34 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
14.07 21:20:34 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
14.07 21:20:34 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
14.07 21:20:34 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
14.07 21:20:34 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
14.07 21:20:34 [Server] WARN at com.hpspells.core.HPS.onEnable(HPS.java:170)
14.07 21:20:34 [Server] WARN at com.hpspells.core.util.ReflectionsReplacement.getSubtypesOf(ReflectionsReplacement.java:81)
14.07 21:20:34 [Server] WARN at com.hpspells.core.util.ReflectionsReplacement.getClassNamesFromPackage(ReflectionsReplacement.java:46)
14.07 21:20:34 [Server] WARN at java.util.jar.JarFile.<init>(Unknown Source)
14.07 21:20:34 [Server] WARN at java.util.jar.JarFile.<init>(Unknown Source)
14.07 21:20:34 [Server] WARN at java.util.zip.ZipFile.<init>(Unknown Source)
14.07 21:20:34 [Server] WARN at java.util.zip.ZipFile.<init>(Unknown Source)
14.07 21:20:34 [Server] WARN at java.util.zip.ZipFile.open(Native Method)
14.07 21:20:34 [Server] WARN java.io.FileNotFoundException: /plugins/HarryPotterSpells v1.1.9.jar (No such file or directory)
14.07 21:20:34 [Server] WARN An error occurred whilst registering some/all of the commands.
14.07 21:20:34 [Server] INFO Only enable if you want to enable debugging mode
14.07 21:20:34 [Server] INFO ############################ #
14.07 21:20:34 [Server] INFO ## http://tiny.cc/hpsconf ## #
14.07 21:20:34 [Server] INFO ## General Configuration  ## #
14.07 21:20:34 [Server] INFO ############################ #
14.07 21:20:34 [Server] INFO Registered 3 wand materials!
14.07 21:20:34 [Server] WARN at java.lang.Thread.run(Unknown Source)
14.07 21:20:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
14.07 21:20:34 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
14.07 21:20:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
14.07 21:20:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
14.07 21:20:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
14.07 21:20:34 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
14.07 21:20:34 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
14.07 21:20:34 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
14.07 21:20:34 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
14.07 21:20:34 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
14.07 21:20:34 [Server] WARN at com.hpspells.core.HPS.onEnable(HPS.java:85)
14.07 21:20:34 [Server] WARN at com.hpspells.core.spell.SpellManager.<init>(SpellManager.java:55)
14.07 21:20:34 [Server] WARN at com.hpspells.core.util.ReflectionsReplacement.getSubtypesOf(ReflectionsReplacement.java:81)
14.07 21:20:34 [Server] WARN at com.hpspells.core.util.ReflectionsReplacement.getClassNamesFromPackage(ReflectionsReplacement.java:46)
14.07 21:20:34 [Server] WARN at java.util.jar.JarFile.<init>(Unknown Source)
14.07 21:20:34 [Server] WARN at java.util.jar.JarFile.<init>(Unknown Source)
14.07 21:20:34 [Server] WARN at java.util.zip.ZipFile.<init>(Unknown Source)
14.07 21:20:34 [Server] WARN at java.util.zip.ZipFile.<init>(Unknown Source)
14.07 21:20:34 [Server] WARN at java.util.zip.ZipFile.open(Native Method)
14.07 21:20:34 [Server] WARN java.io.FileNotFoundException: /plugins/HarryPotterSpells v1.1.9.jar (No such file or directory)
14.07 21:20:34 [Server] WARN An error occurred whilst registering some/all of the spells.
14.07 21:20:34 [Server] INFO Debug: /plugins/HarryPotterSpells/Locale/es-spanish.properties
14.07 21:20:34 [Server] ERROR Could not generate language file /plugins/HarryPotterSpells/Locale/es-spanish.properties Ignore this message if you arent using this language
14.07 21:20:34 [Server] ERROR Could not generate language file /plugins/HarryPotterSpells/Locale/es-spanish.properties Ignore this message if you arent using this language
14.07 21:20:34 [Server] ERROR Could not generate language file /plugins/HarryPotterSpells/Locale/es-spanish.properties Ignore this message if you arent using this language
14.07 21:20:34 [Server] INFO Debug: /plugins/HarryPotterSpells/Locale/de-german.properties
14.07 21:20:34 [Server] ERROR Could not generate language file /plugins/HarryPotterSpells/Locale/de-german.properties Ignore this message if you arent using this language
14.07 21:20:34 [Server] ERROR Could not generate language file /plugins/HarryPotterSpells/Locale/de-german.properties Ignore this message if you arent using this language
14.07 21:20:34 [Server] INFO Debug: /plugins/HarryPotterSpells/Locale/nl-dutch.properties
14.07 21:20:34 [Server] ERROR Could not generate language file /plugins/HarryPotterSpells/Locale/nl-dutch.properties Ignore this message if you arent using this language
14.07 21:20:34 [Server] INFO Debug: /plugins/HarryPotterSpells/Locale/us-english.properties
14.07 21:20:34 [Server] INFO Enabling HarryPotterSpells v1.1.9 BETA
I'm not sure what to do, I've tried reinstalling the plugin multiple times and I feel like the base file on the bukkit page may be missing some files and may need to be replaced with what you're using? Thank you for your time in advance. :)

**Comment by jacklin213** [comment]
@FreralCat make a copy of your ```/plugins/HarryPotterSpells``` folder, delete the original and run the server again, see if that will fix the problem. If it does, copy your config files over 1 by 1. Then everything should be back to normal

**Comment by jacklin213** [comment]
Closed as Op no longer replying to thread. Feel free to reopen an issue if it persists
