### ISSUE TITLE
1.13

### ISSUE THREAD

**Issue by ZeonBT** [HarryPotterSpells/HarryPotterSpells#73]
Hey it’s that horrid time where Mojang update any muck things up though I’ll let you know what’s been effected I’ve sent you a message on bukkit

**Comment by ZeonBT** [comment]
I HAVE MADE A LIST OF ALL SPELLS AND PROBLEMS 

- Accio - WORKS
- Aguamenti - WORKS (PARTICLE DOES NOT)
- Alarte Ascendare - WORKS (PARTICLE DOES NOT)
- Alohomora - WORKS (PARTICLE DOES NOT)
- Aparecium - WORKS NOT NOT ON PLAYER (PARTICLE DOES NOT)
- Arania Exumai - WORKS (PARTICLE DOES NOT)
- Avada Kedavra - WORKS (PARTICLE DOES NOT)
- Avis - WORKS
- Bauleo - WORKS
- Bubble Head Charm - dosent work on self like before
- Confringo - WORKS
- Confundo - DOES NOT WORK
- Crucio - WORKS (PARTICLE DOES NOT)
- Colloportus - WORKS (PARTICLE DOES NOT)		
- Deprimo - NEVER WORKED TBH
- Enderchest - WORKS
- Episkey - WORKS (PARTICLE DOES NOT) 
- Evanesco - WORKS
- Expelliarmus - SPELL WORKS BUT DOES NOT DISHARM (PARTICLE DOES NOT)
- Finite Incantatum - DOES NOT WORK ON PLAYER ANYMORE 
- Glacius - WORKS
- Homenum Revelio - DOES NOT WORK FULLY GAVE OUT 2 TINY SPARKS
- Incendio - WORKS
- Legilimens - WORKS
- Magna Tonitrus - WORKS
- Morsmordre - WORKS
- Multicorfors - ONLY COLOURS SHEEPS, DOES NOT CHANGE WOOL BLOCKS
- Obscuro - WORKS
- Orchideous - WORKS
- Petrificus Totalus - WORKS but only last 2 seconds (PARTICLE DOES NOT)
- Reducto - DOES NOT WORK
- Refilling Charm - WORKS
- Reparo - WORKS
- Sectumsempra - WORKS (PARTICLE DOES NOT)
- Silencio - SHOOTS SPARKS BUT DIDNT WORK
- Sonorus - works kinda but it doesnt make it shout
- Spongify - WORKS
- Stupefy - WORKS (RESPARKS DO NOT)
- Time - WORKS
- Tree - WORKS
- Point Me - WORKS
- Wingardium Leviosa - WORKS 
- Flame Freezing Charm - WORKS
- Workbench - WORKS
- Weather - - WORKS (PARTICLE DOES NOT)

**Comment by ZeonBT** [comment]
Is this what you wanted ?
any thing else i can help with let me know

**Comment by jacklin213** [comment]
https://github.com/HarryPotterSpells/HarryPotterSpells/blob/360f817fc363059daa06e61a69d68be851e66baf/src/com/hpspells/core/command/Teach.java#L78
Spacing bug here that needs to be fixed too
