### ISSUE TITLE
Given Wands do not allow spell to be equipped. 

### ISSUE THREAD

**Issue by bvoignier** [HarryPotterSpells/HarryPotterSpells#94]
**Please complete the following information):**
 - OS: [e.g. Windows/Linux/iOS]
 - Server type: [e.g Spigot/Craftbukkit/Others]
 - Server Version [e.g. 1.12.2 R0.1-Snapshot] ```/version``` to find this out
 - HPS Version [e.g. 1.1.9 BETA] Use ```/version harrypotterspells``` to find this out
 - List of plugins. Use ```/plugin``` to find this out
 - Complete server log

If it's a configuration issue, please also supply the config file.
You can use pastebin.com for the server log and configuration file.

**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by bvoignier** [comment]
I gave a wand after an RPG event. I only want the "grand high witch" to be able to give out wands. wand wont cast magic spells.

**Comment by bvoignier** [comment]
I have Brewery, HarrypotterSpells, LuckPerms, (even after adding full permission to commands still not working, Quests, SerialKey, and TamableFoxes.

**Comment by bvoignier** [comment]
Im stupid, I did not give permission to harrypotterspells.cast for the user

**Comment by jacklin213** [comment]
Glad you were able to figure this out 👍
